add_subdirectory(gstrands/AST)
add_subdirectory(gstrands/Basic)
add_subdirectory(gstrands/Frontend)
add_subdirectory(gstrands/Lex)
add_subdirectory(gstrands/Parse)
add_subdirectory(gstrands/Project)
add_subdirectory(gstrands/Sema)
add_subdirectory(gstrands/Vocab)
add_subdirectory(gstrands/Model)
add_subdirectory(gstrands/Runtime)